### ISSUE TITLE
Cannot validate argument on parameter 'InputObject'

### ISSUE THREAD

**Issue by kasunsjc** [vinijmoura/Azure-DevOps#17]
I was trying to run the AllReport script as below. But throw an error for table inserts.  Can you help me to how to resolve this.

.\Processes.ps1 -PAT PAT  -Organization Org -Connstr "Server=tcp:dbname-dev.database.windows.net,1433;Initial Catalog=azuredevopsreports;Persist Security Info=False;User ID=sqladmin;Password=Password;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

Write-SqlTableData: C:\Users\AzureDevOpsReports\Azure-DevOps\AllReports\PowerShell\Extensions.ps1:31:69
Line |
  31 |  … rite-SqlTableData -InputData $InstalledExtensions -InputObject $table
     |                                                                   ~~~~~~
     | Cannot validate argument on parameter 'InputObject'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
InvalidOperation: C:\Users\AzureDevOpsReports\Azure-DevOps\AllReports\PowerShell\Users.ps1:15:1

When I troubleshoot more I notice the DB connection is not made from the script.  Failed with the following error.
![image](https://user-images.githubusercontent.com/16514562/230340309-74ca20d4-b904-42b9-919e-f41f086c1d78.png)

**Comment by vinijmoura** [comment]
Hello @kasunsjc 
I sent an e-mail to you!

**Comment by kasunsjc** [comment]
Sure we can have a call on 13th April 5.00 P.M CET time.

**Comment by vinijmoura** [comment]
Sure, send me an invitation!

**Comment by vwasthename** [comment]
I'm having the same issue. Any update on this issue?

**Comment by vinijmoura** [comment]
Hello @vwasthename 
Please send me an email so that I can contact you!

**Comment by tgiannelli-rm** [comment]
@vinijmoura  --- I'm getting this error as well... can you email me at tgiannelli@rockymountaineer.com

**Comment by vinijmoura** [comment]
Other person get the same problem. Please try it!!!
If ok, I will create a commit :-)

On Processess.ps1 

Change:

_#$sqlcc = New-Object -TypeName System.Data.SqlClient.SqlConnection -ArgumentList $Connstr
#$sc = New-Object -TypeName Microsoft.SqlServer.Management.Common.ServerConnection -ArgumentList $sqlcc
#$srv = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -ArgumentList $sc
#$db = $srv.Databases["azuredevopsreports"]_

With:

$sc = New-Object -TypeName Microsoft.SqlServer.Management.Common.ServerConnection -ArgumentList 'dbhost.database.windows.net', 'sqladmin', 'xxpasswordxx'
try {
    $sc.Connect()
    Write-Host "Connected to the server using SMO."
} catch {
    Write-Host "Error: $($_.Exception.Message)"
}

$srv = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -ArgumentList $sc
$db = $srv.Databases["azuredevopsreports"]

**Comment by tgiannelli-rm** [comment]
Giving this a try now...

I'm assuming that I replace  'dbhost.database.windows.net', 'sqladmin', 'xxpasswordxx' with my specific connection details.

do I need to change the execution script .\Processes.ps1 -PAT {{PAT}} -Organization {{Organization}}  -Connstr {{Connection string from database}} t oexclude the -Connstr?

Tom Giannelli |   Director, Platform Delivery
t 604.335.7938    m 604.349.6463
#1100 - 980 Howe Street, Vancouver, British Columbia, V6Z 0C8 Canada


________________________________
From: Vinicius Moura ***@***.***>
Sent: Wednesday, May 17, 2023 11:54 AM
To: vinijmoura/Azure-DevOps ***@***.***>
Cc: Tom Giannelli (he/him) ***@***.***>; Comment ***@***.***>
Subject: [External]: Re: [vinijmoura/Azure-DevOps] Cannot validate argument on parameter 'InputObject' (Issue #17)


  CAUTION: This email is from an external source.

Other person get the same problem. Please try it!!!
If ok, I will create a commit :-)

On Processess.ps1

Change:

#$sqlcc = New-Object -TypeName System.Data.SqlClient.SqlConnection -ArgumentList $Connstr
#$sc = New-Object -TypeName Microsoft.SqlServer.Management.Common.ServerConnection -ArgumentList $sqlcc
#$srv = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -ArgumentList $sc
#$db = $srv.Databases["azuredevopsreports"]

With:

$sc = New-Object -TypeName Microsoft.SqlServer.Management.Common.ServerConnection -ArgumentList 'dbhost.database.windows.net', 'sqladmin', 'xxpasswordxx'
try {
$sc.Connect()
Write-Host "Connected to the server using SMO."
} catch {
Write-Host "Error: $($_.Exception.Message)"
}

$srv = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -ArgumentList $sc
$db = $srv.Databases["azuredevopsreports"]

**Comment by vinijmoura** [comment]
Yes, try put these parameters
After that, processes.ps1 wil be required 3 parameters (server, use, pwd) and I'll exclude Connstr

**Comment by tgiannelli-rm** [comment]
Error: Exception calling "Connect" with "0" argument(s): "Failed to connect to server RMITPRODDB01.database.windows.net."

Tom Giannelli |   Director, Platform Delivery
t 604.335.7938    m 604.349.6463
#1100 - 980 Howe Street, Vancouver, British Columbia, V6Z 0C8 Canada

________________________________
From: Vinicius Moura ***@***.***>
Sent: Wednesday, May 17, 2023 11:54 AM
To: vinijmoura/Azure-DevOps ***@***.***>
Cc: Tom Giannelli (he/him) ***@***.***>; Comment ***@***.***>
Subject: [External]: Re: [vinijmoura/Azure-DevOps] Cannot validate argument on parameter 'InputObject' (Issue #17)


  CAUTION: This email is from an external source.

Other person get the same problem. Please try it!!!
If ok, I will create a commit :-)

On Processess.ps1

Change:

#$sqlcc = New-Object -TypeName System.Data.SqlClient.SqlConnection -ArgumentList $Connstr
#$sc = New-Object -TypeName Microsoft.SqlServer.Management.Common.ServerConnection -ArgumentList $sqlcc
#$srv = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -ArgumentList $sc
#$db = $srv.Databases["azuredevopsreports"]

With:

$sc = New-Object -TypeName Microsoft.SqlServer.Management.Common.ServerConnection -ArgumentList 'dbhost.database.windows.net', 'sqladmin', 'xxpasswordxx'
try {
$sc.Connect()
Write-Host "Connected to the server using SMO."
} catch {
Write-Host "Error: $($_.Exception.Message)"
}

$srv = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -ArgumentList $sc
$db = $srv.Databases["azuredevopsreports"]

**Comment by tgiannelli-rm** [comment]
something to note we use  AD authentication.


Tom Giannelli |   Director, Platform Delivery
t 604.335.7938    m 604.349.6463
#1100 - 980 Howe Street, Vancouver, British Columbia, V6Z 0C8 Canada

________________________________
From: Vinicius Moura ***@***.***>
Sent: Wednesday, May 17, 2023 12:07 PM
To: vinijmoura/Azure-DevOps ***@***.***>
Cc: Tom Giannelli (he/him) ***@***.***>; Comment ***@***.***>
Subject: [External]: Re: [vinijmoura/Azure-DevOps] Cannot validate argument on parameter 'InputObject' (Issue #17)


  CAUTION: This email is from an external source.

Yes, try put these parameters
After that, processes.ps1 wil be required 3 parameters (server, use, pwd) and I'll exclude Connstr

**Comment by tgiannelli-rm** [comment]
Sorry hit send too soon... my DBA gave me this connection string as an example to use... might be why I cannot connect.

$Connstr = "Server=YourServerName;Database=YourDatabaseName;Integrated Security=SSPI;"

Tom Giannelli |   Director, Platform Delivery
t 604.335.7938    m 604.349.6463
#1100 - 980 Howe Street, Vancouver, British Columbia, V6Z 0C8 Canada

________________________________
From: Vinicius Moura ***@***.***>
Sent: Wednesday, May 17, 2023 12:07 PM
To: vinijmoura/Azure-DevOps ***@***.***>
Cc: Tom Giannelli (he/him) ***@***.***>; Comment ***@***.***>
Subject: [External]: Re: [vinijmoura/Azure-DevOps] Cannot validate argument on parameter 'InputObject' (Issue #17)


  CAUTION: This email is from an external source.

Yes, try put these parameters
After that, processes.ps1 wil be required 3 parameters (server, use, pwd) and I'll exclude Connstr

**Comment by vinijmoura** [comment]
Please, try again connection and send me a feedback!

**Comment by tgiannelli-rm** [comment]
Here is the output.
[cid:b7ead269-f363-4273-b17a-55617c9e9ed5]

This is what the connection String looks like.

$sc = New-Object -TypeName Microsoft.SqlServer.Management.Common.ServerConnection -ArgumentList 'rmitproddb01.database.windows.net', ***@***.***', 'xxxxxx'
try {
$sc.Connect()
Write-Host "Connected to the server using SMO."
} catch {
Write-Host "Error: $($_.Exception.Message)"


Tom Giannelli |   Director, Platform Delivery
t 604.335.7938    m 604.349.6463
#1100 - 980 Howe Street, Vancouver, British Columbia, V6Z 0C8 Canada

________________________________
From: Vinicius Moura ***@***.***>
Sent: Wednesday, May 17, 2023 1:46 PM
To: vinijmoura/Azure-DevOps ***@***.***>
Cc: Tom Giannelli (he/him) ***@***.***>; Comment ***@***.***>
Subject: [External]: Re: [vinijmoura/Azure-DevOps] Cannot validate argument on parameter 'InputObject' (Issue #17)


  CAUTION: This email is from an external source.

Please, try again connection and send me a feedback!

**Comment by vinijmoura** [comment]
did you get the connection?

**Comment by tgiannelli-rm** [comment]
no I didn't get the connection.

Tom Giannelli |   Director, Platform Delivery
t 604.335.7938    m 604.349.6463
#1100 - 980 Howe Street, Vancouver, British Columbia, V6Z 0C8 Canada

________________________________
From: Vinicius Moura ***@***.***>
Sent: Wednesday, May 17, 2023 2:15 PM
To: vinijmoura/Azure-DevOps ***@***.***>
Cc: Tom Giannelli (he/him) ***@***.***>; Comment ***@***.***>
Subject: [External]: Re: [vinijmoura/Azure-DevOps] Cannot validate argument on parameter 'InputObject' (Issue #17)


  CAUTION: This email is from an external source.

did you get the connection?

**Comment by vinijmoura** [comment]
Ok. Let's create meeting tomorrow!

**Comment by tgiannelli-rm** [comment]
Thursday is really busy.  Does Friday look okay for you?

Tom Giannelli
Director, Platform Delivery
Rocky Mountaineer
________________________________
From: Vinicius Moura ***@***.***>
Sent: Wednesday, May 17, 2023 7:36:19 PM
To: vinijmoura/Azure-DevOps ***@***.***>
Cc: Tom Giannelli (he/him) ***@***.***>; Comment ***@***.***>
Subject: [External]: Re: [vinijmoura/Azure-DevOps] Cannot validate argument on parameter 'InputObject' (Issue #17)


  CAUTION: This email is from an external source.

Ok. Let's create meeting tomorrow!

**Comment by vinijmoura** [comment]
Hello my friends,

I just commit a new version of Processes.ps1 file that I believe will fix this problem!
@vwasthename 
@kasunsjc 
@tgiannelli-rm 
@EwertonJordao 

I'm closing this issue!
