### ISSUE TITLE
DB Connection error with Processes.ps1

### ISSUE THREAD

**Issue by successhawk** [vinijmoura/Azure-DevOps#21]
I was getting the folowing error when I executed the Processes.ps1 code
```
Line |
  10 |  $table = $db.Tables["FeedPackageVersions"]
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.

```
I did some refactoring of the code and ultimately it seemed like there was something wrong with how the $srv object is being created because it wasn't using the $connstr, and I really don't like that even when I turned on Debug the current solution doesn't give the "root cause" connection error.  Ultimately, I think I found a better way.

**Here is how I fixed it using the **Get-SqlDatabase** cmdlet.** Replace the following commented out code with one line of code that follows
```
# $sqlcc = New-Object -TypeName System.Data.SqlClient.SqlConnection -ArgumentList $Connstr
# $sc = New-Object -TypeName Microsoft.SqlServer.Management.Common.ServerConnection -ArgumentList $sqlcc
# $srv = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -ArgumentList $sc
# $db = $srv.Databases["azuredevopsreports"]
$db = Get-SqlDatabase -Name "azuredevopsreports" -ConnectionString $Connstr

```

**Comment by vinijmoura** [comment]
Good suggestion! I will test here and create a commit!

**Comment by vinijmoura** [comment]
Hello. Thanks for your contribution. I just include your suggestion on my code! #

**Comment by vinijmoura** [comment]
New connection database!
