### ISSUE TITLE
Is it possible to get the YAML based Stage approvers names?

### ISSUE THREAD

**Issue by kasunsjc** [vinijmoura/Azure-DevOps#23]
We have approvers in the production stage. We use environment for adding approvers. We would like to get the approvers name. For pipeline we use YAML based pipeline. 

In the report I can see there is a report for approvers. is it possible to get approvers name from it

**Comment by vinijmoura** [comment]
YEs. totally possible!
I will create a new report! \o/

**Comment by vinijmoura** [comment]
The new report was delivered: https://vinijmoura.medium.com/how-to-list-all-environments-and-approvers-on-azure-devops-f9ffaa0d5a75
