### ISSUE TITLE
Environment and Approval/Checks Report

### ISSUE THREAD

**Issue by wpschaub** [vinijmoura/Azure-DevOps#4]
**Is your feature request related to a problem? Please describe.**
Not related to a problem - it extends your https://vinijmoura.medium.com/how-to-create-dashboard-to-visualize-environments-and-deployments-on-azure-devops-319ddb1614f4 report.

**Describe the solution you'd like**
The https://vinijmoura.medium.com/how-to-create-dashboard-to-visualize-environments-and-deployments-on-azure-devops-319ddb1614f4 report generates a great view on the "life of the pipelines and environments", invaluable for release management. Would be great to have another view/report of the environments and their approvals/checks, used to verify that environments have been correctly configured and are not drifting in terms of configuration consistency.

**Comment by vinijmoura** [comment]
@wpschaub, Can you include please a prototype? :-)

**Comment by wpschaub** [comment]
@vinijmoura what do you understand with a prototype? A PowerShell script and/or a report sketch showing type of information expected?

**Comment by vinijmoura** [comment]
@wpschaub  report sketch (image)

**Comment by wpschaub** [comment]
Here is what I am envisioning:
![Environments](https://user-images.githubusercontent.com/12176555/124636997-09e0d400-de3e-11eb-8153-80f2b38bd301.png)

A list of all environments for selected project(s) and an indicator which of the approval/checks have been defined. For example, immediately we would see that the SHARED-PR is missing the required template check.

What the report does not show, is the state of the security setup ... but that is a topic for another report :)

**Comment by vinijmoura** [comment]
@wpschaub I will use this API
https://docs.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/check%20configurations/query?view=azure-devops-rest-6.1
But I can't create a respective body! Can you help me here?

**Comment by wpschaub** [comment]
We will have to first run the https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments/list?view=azure-devops-rest-6.1 to gather the environment names and IDs.

**Comment by vinijmoura** [comment]
> We will have to first run the https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments/list?view=azure-devops-rest-6.1 to gather the environment names and IDs.

Yes, I do. The problem is to compose a body :-(

**Comment by wpschaub** [comment]
I will investigate when I get a break today.

**Comment by vinijmoura** [comment]
> I will investigate when I get a break today.

I can create the body 🥇 

Now, I'll create PowerShell, Report and post! Stay tuned!!!

**Comment by vinijmoura** [comment]
@wpschaub Can I publish? 🥇 

![image](https://user-images.githubusercontent.com/8333012/124815410-9de59500-df3d-11eb-8daf-fbc57970a56f.png)

**Comment by vinijmoura** [comment]
Include on commit "Create report to show all Environments and respective Approvals and Checks #4"

**Comment by wpschaub** [comment]
Excellent work @vinijmoura! I will raise awareness internally and on twitter!
