### ISSUE TITLE
List all users and group permissions on OnPrem

### ISSUE THREAD

**Issue by vinaysandela** [vinijmoura/Azure-DevOps#5]
Can we do the same for OnPrem Azure DevOps?
Looking for audit report for listing all users and group permissions on Azure devops

**Comment by vinijmoura** [comment]
az devops cli does not work with on-prem. :-(

To use REST API in on-prem, we use this documentation:
https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1#components-of-a-rest-api-requestresponse-pair
**TFS: {server:port}/tfs/{collection} (the default port is 8080, and the value for collection should be DefaultCollection but can be any collection)**

Here you should use REST API
- list users: https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/users/list?view=azure-devops-rest-6.0&viewFallbackFrom=azure-devops-server-rest-5.0

- Memebrship list - https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/memberships/list?view=azure-devops-rest-6.0
