### ISSUE TITLE
Report: Last activities at Projects

### ISSUE THREAD

**Issue by aldodfm** [vinijmoura/Azure-DevOps#6]
Hello @vinijmoura ,
FOr a good maintenance of AzDO org, i think that it would be great to have a report where is a list of projects (and the owners of the projects) and last activity regarding last update in Boards / work items, Repos last update, TEst Plans last update, Pipelines last update, Wiki last update, and so on.
Then it will be useful to decommission projects or contact with admins to know what happens with the project.

;)

**Comment by vinijmoura** [comment]
Hello @aldodfm 
I just created a report based on Project Stats :-)
See the link https://vinijmoura.medium.com/how-to-project-stats-mapping-on-azure-devops-63ca0f0d4ca
