### ISSUE TITLE
Issue with JSON

### ISSUE THREAD

**Issue by JackPlacek** [vinijmoura/Azure-DevOps#8]
Hi,

The dashboard is very useful and all the functions used to work. However, now there is an error that says that there are extra characters at the end of JSON input:
![image](https://user-images.githubusercontent.com/105062316/167150262-5702f0b8-76bc-4370-a70f-5b28bea77193.png)

Any idea how it can be fixed?

**Comment by vinijmoura** [comment]
what specifically is this report?

**Comment by JackPlacek** [comment]
Hi,
I created the same report as yours (based on your great pbix file). Currently in both reports I see the same error.
So it is getting users entitlements (so users vs.  license type, etc)  from DevOps using query and following source address:

= Json.Document(Web.Contents("https://vsaex.dev.azure.com/" & Organization  & "/_apis/userentitlements?api-version=4.1-preview.1"))

What is interesting, I entered this address in the web browser, copied JSON to the file, opened the JSON file in PowerBI and there were no issues then loading data to PowerBi. 

Maybe there is something wrong with the authorization? 


Jacek

**Comment by JackPlacek** [comment]
However, this error appears just after uploading your file and without changing anything (like for example Organization parameter): 
![image](https://user-images.githubusercontent.com/105062316/167156976-d5bb04c6-5e03-4dc0-a386-81f98c0bb274.png)

I can't recall such error in the past. The dashboard was working very well many months.

**Comment by vinijmoura** [comment]
@JackPlacek I'm closing the issue after our talk. Thanks for your feedback.
Resolution: create PAT and connect report using our user and PAT.
